#! /bin/sh
#xsetroot -cursor_name left_ptr
#xsetroot -xcf /usr/share/icons/Bibata-Modern-Ice/cursors/left_ptr 60
#xinput set-prop '17' 298 -0.9
xsetroot -xcf .icons/oreo_spark_lite_cursors/cursors/left_ptr 16
lxsession &
#picom &
xrandr --dpi 96
pgrep -x polybar > /dev/null || polybar -r example &
nitrogen --restore &
pamixer --set-volume 100 &
dunst &
bash /home/octo/scripts/start_openrgb.sh &
unclutter --timeout 2 --ignore-scrolling --jitter 50 &
#xcape &
xcape -e 'Super_L=Alt_L|F12' &
xsetwacom set 14 MapToOutput HEAD-0 &
pgrep -x sxhkd > /dev/null || sxhkd &
ssh-agent -s &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a '*:rofi' state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Steam state=floating 
bspc rule -a qutebrowser state=floating
