#! /bin/sh
#xsetroot -cursor_name left_ptr
#xsetroot -xcf /usr/share/icons/Bibata-Modern-Ice/cursors/left_ptr 60
#xinput set-prop '17' 298 -0.9
xsetroot -xcf .icons/oreo_spark_lite_cursors/cursors/left_ptr 16
lxsession &
picom --config ~/.config/picom/picom.conf &
xrandr --dpi 100x100
xrandr --output DP-0 --primary
pgrep -x polybar > /dev/null || polybar -r left &
pgrep -x polybar > /dev/null || polybar -r right &
pgrep -x polybar > /dev/null || polybar -r center &
pgrep -x polybar > /dev/null || polybar -r starters &
pgrep -x polybar > /dev/null || polybar -r powerbar &
pgrep -x polybar > /dev/null || polybar -r stats &
xset s off & 
nitrogen --restore &
pamixer --set-volume 100 &
dunst &
bash /home/octo/scripts/start_openrgb.sh &
unclutter --timeout 2 --ignore-scrolling --jitter 50 &
#xcape &
xcape -e 'Super_L=Alt_L|F12' &
xsetwacom set "Wacom Intuos S Pen stylus" MapToOutput HEAD-0 &
pgrep -x sxhkd > /dev/null || sxhkd &
ssh-agent -s &

bspc monitor DP-0 -d I
bspc monitor HDMI-0 -d II

bspc config border_width         5
bspc config window_gap           15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config focused_border_color "#FFFFFF"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a '*:rofi' state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Steam state=floating 
bspc rule -a qutebrowser state=floating
bspc rule -a '*:UltiMaker-Cura' state=floating
#bspc rule -a 'osu! state=floating
#bspc rule -a '*' state=floating
